#!/bin/sh
set -eu

: "${ORGANIGRAM_OPENDESK_ENABLED:=false}"
: "${ORGANIGRAM_OPENDESK_PORTAL_URL:=}"
: "${ORGANIGRAM_OPENDESK_ICS_URL:=}"
: "${ORGANIGRAM_OPENDESK_KEYCLOAK_ISSUER_URL:=}"
: "${ORGANIGRAM_OPENDESK_OIDC_CLIENT_ID:=organigram}"
: "${ORGANIGRAM_OPENDESK_POST_LOGOUT_REDIRECT_URL:=}"
: "${ORGANIGRAM_OPENDESK_NAVIGATION_LANGUAGE:=de-DE}"
: "${ORGANIGRAM_OPENDESK_SUITE_LABEL:=openDesk}"

envsubst \
  '${ORGANIGRAM_OPENDESK_ENABLED} ${ORGANIGRAM_OPENDESK_PORTAL_URL} ${ORGANIGRAM_OPENDESK_ICS_URL} ${ORGANIGRAM_OPENDESK_KEYCLOAK_ISSUER_URL} ${ORGANIGRAM_OPENDESK_OIDC_CLIENT_ID} ${ORGANIGRAM_OPENDESK_POST_LOGOUT_REDIRECT_URL} ${ORGANIGRAM_OPENDESK_NAVIGATION_LANGUAGE} ${ORGANIGRAM_OPENDESK_SUITE_LABEL}' \
  < /usr/share/nginx/html/runtime-config.template.js \
  > /usr/share/nginx/html/runtime-config.js

exec nginx -g 'daemon off;'
