apiVersion: apps/v1
kind: Deployment
metadata:
  name: organigram
  namespace: organigram
spec:
  template:
    spec:
      containers:
        - name: organigram
          env:
            - name: ORGANIGRAM_OPENDESK_ENABLED
              value: "true"
            - name: ORGANIGRAM_OPENDESK_PORTAL_URL
              value: "https://portal.cognitive-hive.ai/univention/portal/"
            - name: ORGANIGRAM_OPENDESK_KEYCLOAK_ISSUER_URL
              value: "https://id.cognitive-hive.ai/realms/opendesk"
            - name: ORGANIGRAM_OPENDESK_OIDC_CLIENT_ID
              value: "organigram"
            - name: ORGANIGRAM_OPENDESK_POST_LOGOUT_REDIRECT_URL
              value: "https://portal.cognitive-hive.ai/univention/portal/"
            - name: ORGANIGRAM_OPENDESK_NAVIGATION_LANGUAGE
              value: "de-DE"
            - name: ORGANIGRAM_OPENDESK_SUITE_LABEL
              value: "openDesk"
            - name: ORGANIGRAM_OPENDESK_PORTAL_SERVER_URL
              value: "http://ums-portal-server.opendesk.svc.cluster.local/portal"
            - name: ORGANIGRAM_OPENDESK_NEXTCLOUD_URL
              value: "https://drive.cognitive-hive.ai"
            - name: ORGANIGRAM_OPENDESK_NEXTCLOUD_FOLDER
              value: "Organigramme"
            - name: ORGANIGRAM_OPENDESK_NEXTCLOUD_PRINCIPAL_CLAIM
              value: "opendesk_useruuid"
